# Generated by Django 5.2.17 on 2026-08-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('candidate', 'Candidate'), ('examiner', 'Examiner'), ('admin', 'Admin')], default='candidate', max_length=16),
        ),
    ]
