# Generated by Django 5.2.17 on 2026-08-06 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('advanced', 'Advanced')], max_length=16)),
                ('description', models.TextField(blank=True)),
                ('icon_url', models.URLField(blank=True)),
                ('marketing_url', models.URLField(blank=True)),
                ('external_ref', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=16)),
                ('type', models.CharField(choices=[('objective', 'Objective'), ('subjective', 'Subjective')], default='objective', max_length=16)),
                ('duration_minutes', models.PositiveIntegerField(default=45, help_text='Determined by the exam type: 45 for objective, 2160 (36h) for subjective.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exams',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='booking',
            name='certification',
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='one_open_booking_per_certification',
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('duration_minutes', 45), ('type', 'objective')), models.Q(('duration_minutes', 2160), ('type', 'subjective')), _connector='OR'), name='exam_duration_matches_type'),
        ),
        migrations.AddField(
            model_name='booking',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='exam.exam'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'booked')), fields=('candidate', 'exam'), name='one_open_booking_per_exam'),
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
    ]
