# Generated by Django 5.2.17 on 2026-08-17 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['updated_at']},
        ),
        migrations.RemoveField(
            model_name='exam',
            name='candidate_name',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='scheduled_at',
        ),
    ]
