# Generated by Django 5.2.17 on 2026-08-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_exam_remove_booking_certification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='duration_minutes',
            field=models.PositiveIntegerField(help_text='Determined by the exam type: 45 for objective, 2160 (36h) for subjective.'),
        ),
    ]
