# Generated by Django 5.2.17 on 2026-08-20 15:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_alter_exam_options_remove_exam_candidate_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('certificate_file', models.FileField(upload_to='certificates/')),
            ],
            options={
                'db_table': 'certificates',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='exambooking',
            name='one_open_booking_per_exam',
        ),
        migrations.AddField(
            model_name='exam',
            name='maximum_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='passing_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exambooking',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exambooking',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exambooking',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='graded_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exambooking',
            name='marks_obtained',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exambooking',
            name='maximum_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exambooking',
            name='passing_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exambooking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('attended', 'Attended'), ('no_show', 'No show'), ('under_review', 'Under review'), ('graded', 'Graded')], default='booked', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='exambooking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['booked', 'under_review', 'attended'])), fields=('candidate', 'exam'), name='one_open_booking_per_exam'),
        ),
        migrations.AddField(
            model_name='certificates',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificate', to='exam.exambooking'),
        ),
    ]
