# Generated by Django 5.2.17 on 2026-08-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_certificates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='subject_level',
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=16),
        ),
    ]
