# Generated by Django 5.2.17 on 2026-08-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_remove_subject_subject_level_exam_exam_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='question_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='question_selection',
            field=models.CharField(choices=[('random', 'Randomize From Pool'), ('manual', 'Select Manually')], default='random', max_length=30),
        ),
    ]
