# Generated by Django 5.2.17 on 2026-08-27 08:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_exam_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='image',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_keywords',
        ),
        migrations.RemoveField(
            model_name='video',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='answeroptions',
            name='associated_audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='exam.audio'),
        ),
        migrations.AddField(
            model_name='answeroptions',
            name='associated_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='exam.image'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(upload_to='audio/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'm4a', 'ogg'])]),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.FileField(upload_to='image/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='video/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm'])]),
        ),
    ]
