# Generated by Django 5.2.17 on 2026-08-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_remove_audio_updated_at_remove_image_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('retired', 'Retired')], default='active', max_length=16),
        ),
    ]
