# Generated by Django 5.2.17 on 2026-09-02 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_question_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answeroptions',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='answeroptions',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ExamSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('current_position', models.PositiveSmallIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sheet', to='exam.exambooking')),
            ],
            options={
                'db_table': 'exam_sheets',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamSheetQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('marks', models.PositiveIntegerField()),
                ('written_answer', models.TextField(blank=True)),
                ('marks_awarded', models.PositiveIntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sheet_entries', to='exam.question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chosen_on', to='exam.answeroptions')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.examsheet')),
            ],
            options={
                'db_table': 'exam_sheet_questions',
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('sheet', 'position'), name='one_question_per_sheet_position'), models.UniqueConstraint(fields=('sheet', 'question'), name='no_duplicate_question_on_sheet')],
            },
        ),
    ]
