# Generated by Django 5.2.17 on 2026-09-07 08:34

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_alter_answeroptions_options_answeroptions_position_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exam',
            name='exam_duration_matches_type',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='passing_marks',
        ),
        migrations.AddField(
            model_name='exam',
            name='pass_percentage',
            field=models.PositiveSmallIntegerField(default=70, help_text='Whole percent of the paper needed to pass.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('objective', 'Objective'), ('subjective', 'Subjective'), ('both', 'Both')], default='objective', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('duration_minutes', 45), ('exam_type', 'objective')), models.Q(('duration_minutes', 2160), ('exam_type', 'subjective')), models.Q(('duration_minutes', 2205), ('exam_type', 'both')), _connector='OR'), name='exam_duration_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('exam_type', 'subjective'), ('question_count__isnull', True)), models.Q(models.Q(('exam_type', 'subjective'), _negated=True), ('question_count__isnull', False)), _connector='OR'), name='exam_question_count_matches_type'),
        ),
    ]
