# Generated by Django 5.2.17 on 2026-09-07 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_remove_exam_exam_duration_matches_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exambooking',
            name='one_open_booking_per_exam',
        ),
        migrations.AddField(
            model_name='exambooking',
            name='parent_booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjective_booking', to='exam.exambooking'),
        ),
        migrations.AddField(
            model_name='exambooking',
            name='round_type',
            field=models.CharField(choices=[('objective', 'Objective'), ('subjective', 'Subjective'), ('both', 'Both')], default='objective', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='exambooking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['booked', 'under_review', 'attended'])), fields=('candidate', 'exam', 'round_type'), name='one_open_booking_per_exam'),
        ),
    ]
