# Generated by Django 5.2.17 on 2026-09-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_remove_exambooking_one_open_booking_per_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsheet',
            name='submission_status',
            field=models.CharField(choices=[('self', 'Self'), ('timedout', 'Timed Out')], default='self', max_length=20),
        ),
    ]
