# Generated by Django 5.2.17 on 2026-10-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_examsheet_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsheetquestion',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
