# Generated by Django 5.2.17 on 2026-10-07 11:00

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_examsheetquestion_flagged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsheetquestion',
            name='written_answer',
        ),
        migrations.CreateModel(
            name='SubjectiveSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_repo', models.URLField()),
                ('github_pr', models.URLField()),
                ('test_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='exam.examsheetquestion')),
            ],
            options={
                'db_table': 'subjective_submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
