# Generated by Django 5.2.17 on 2026-08-06 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('booked_timezone', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('attended', 'Attended'), ('no_show', 'No show')], default='booked', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='certifications.certification')),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-scheduled_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'booked')), fields=('candidate', 'certification'), name='one_open_booking_per_certification')],
            },
        ),
    ]
